<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
    <PackageReference Include="System.IO.Ports" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.2.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.11" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="1.1.1" />
  </ItemGroup>

</Project>
