<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mk20Control.Protocol\Mk20Control.Protocol.csproj" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.11" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
